name: demo-vascomm-store
services:
  php:
    type: php:8.0
    via: apache
    webroot: lumen-php/public
  database:
    type: mysql
  pma:
    type: phpmyadmin
  mailhog:
    type: mailhog
  swagger:
    type: lando
    app_mount: false
    services:
      image: swaggerapi/swagger-ui
      ports:
        - '80'
      command: docker run -p 80:8080 swaggerapi/swagger-ui
tooling:
  php:
    service: php
  composer:
    service: php
proxy:
  php:
    - demo-vascomm-store.be-admin.lndo.site
  pma:
    - demo-vascomm-store.pma.lndo.site
  mailhog:
    - demo-vascomm-store.mailhog.lndo.site